@AnteraApp.Api_HostAddress = http://localhost:5212
@Token = paste-a-valid-token-here

GET {{AnteraApp.Api_HostAddress}}/api/pollen/current?latitude=40.4168&longitude=-3.7038
Accept: application/json
Authorization: Bearer {{Token}}
